blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/Arm-Examples/Get-Started-with-Edge-AI/issues
    about: Please search existing issues first. If you have a usage question, open an issue.
